# Generated by Django 5.1.7 on 2025-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('issued_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
